### ISSUE TITLE
Impossible to delete tfchain client

### ISSUE THREAD

**Issue by zaibon** [threefoldtecharchive/jumpscaleX_archived#211]
This is related to #210 
Now that I have 2 clients with the same name, I wanted to clean this up and remove them all.
I tried to do
`j.clients.tfchain.delete(name='testnet')`
This call doesn't raise any error, but the client are not deleted.

I am now stuck with clients I cannot delete

**Comment by zaibon** [comment]
I did found a way to delete them:
![2019-02-28_1674x395_scrot](https://user-images.githubusercontent.com/303164/53567071-650fa700-3b5e-11e9-8e00-8ec65d5d53c2.png)
(sorry for the picture, but I cannot copy from kosmos shell)

So by getting the element from the list return by `j.clients.tfchain.find()` I can get the client can call delete on it. It raises an error, but seems the client is actually gone after that.

**Comment by BolaNasr** [comment]
now it works good : 
![Screenshot from 2019-03-17 17-56-34](https://user-images.githubusercontent.com/10259267/54493956-0d06cd80-48de-11e9-8fc9-4b394bd9dd42.png)


if you need make specific  attributes  unique just add & before the name : 

```
schema = """
@url =  jumpscale.test.1
giturl =  "" (S)
&dest =  "" (S)  #unique attribute
enable = true (B)
"""
```

**Comment by zaibon** [comment]
I tested it seems to work ok indeed.
@GlenDC I let you decide if this solution is good enough for you, if yes we can probably close the issue

**Comment by GlenDC** [comment]
Is it just me, but when I try the following, I no longer find them using a plain `find` call:

```python3
j.clients.tfchain.new("whatever")
j.clients.tfchain.find() # nothing, expected from code perspective, but weird from user
j.clients.tfchain.whatever.save()
j.clients.tfchain.find() # now it does find the client
j.clients.tfchain.delete(name="whatever")
j.clients.tfchain.find() # nothing, as expected
j.clients.tfchain.new("whatever")
j.clients.tfchain.find() # nothing, expected from code perspective, but weird from user
j.clients.tfchain.whatever.save()
j.clients.tfchain.find() # still nothing, not expected (BUG???)
```

**Comment by GlenDC** [comment]
Also, are there unit tests written for this? If so, link them and only close then.

(cc @BolaNasr)

**Comment by BolaNasr** [comment]
@GlenDC Good catch :+1: 
i fixed it , now it works good ( just ```git pull ```)  : 
![Screenshot from 2019-03-19 12-43-30](https://user-images.githubusercontent.com/10259267/54600146-ce3f5780-4a44-11e9-867a-23c84d78c027.png)

**Comment by Dina-Abd-Elrahman** [comment]
- it's working fine for me.

**Comment by Dina-Abd-Elrahman** [comment]
@AhmedHanafy725 to complete unit test.

**Comment by zaibon** [comment]
It still doesn't work here.
```python
kosmos 
JSX> c = j.clients.tfchain.new('testnet1', network_type='TEST')                                                                                                                                                                                
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseConfigs.py", line 57, in new
    raise RuntimeError("can't create , this name already exist")
RuntimeError: can't create , this name already exist

can't create , this name already exist
JSX> j.clients.tfchain.delete('main')                                                                                                                                                                                                          
JSX> c = j.clients.tfchain.new('testnet1', network_type='TEST')                                                                                                                                                                                
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseConfigs.py", line 57, in new
    raise RuntimeError("can't create , this name already exist")
RuntimeError: can't create , this name already exist
```
JSX revision: 7118d6d21c43261c8bfaa3e9614c7854c4fd0e95

Raising to critical

**Comment by AhmedHanafy725** [comment]
https://github.com/threefoldtech/jumpscaleX/issues/236#issuecomment-484122385

**Comment by zaibon** [comment]
I don't agree with the fact that we close this one. So I'll open new issue to explain the real problem: https://github.com/threefoldtech/jumpscaleX/issues/350

**Comment by despiegk** [comment]
all of this should be fixed on development now, behaviour is different per schema, no point to keep open, lets look at it with fresh eye
